[project]
name = "energy-dashboard"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "dtaylor-us", email = "derektaylor.us@gmail.com" }
]
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.29.0",
    "databases>=0.9.0",
    "httpx>=0.27.0",
    "jinja2>=3.1.4",
    "aiosqlite>=0.20.0",
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.7",
    "alembic>=1.13.1",
    "bokeh>=3.4.1",
    "sqlalchemy[asyncio]>=2.0.30",
    "pandas>=2.2.2",
    "aiocache>=0.12.2",
    "instructor>=1.3.2",
    "anthropic>=0.28.0",
    "groq>=0.8.0",
    "openai>=1.30.5",
    "matplotlib>=3.9.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.4.5",
]

[tool.rye.scripts]
dev = "uvicorn energy_dashboard.app:app --reload"
fast_api = "uvicorn energy_dashboard.fast_api:app --reload"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/energy_dashboard"]

[tool.hatch.build.scripts]
energy-dashboard = "energy_dashboard.main:main"
